minVersion: '0.9.0'
github:
    owner: getsentry
    repo: sentry-release-parser
changelogPolicy: none
statusProvider: 
    name: github
preReleaseCommand: ""
targets:
    - name: github
    - name: crates
    - name: npm
