minVersion: '0.22.2'
github:
  owner: getsentry
  repo: sentry-release-parser
changelogPolicy: none
preReleaseCommand: ./scripts/bump-version.sh
targets:
    - name: github
    - name: crates
    - name: npm
    access: public
statusProvider:
  name: github
artifactProvider:
  name: github
