language: node_js
node_js: '10'

install: yarn

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOLCHAIN:-stable}
  - export PATH=~/.cargo/bin/:$PATH

script: make
