[package]
name = "sentry-release-parser"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1.3.3", features = ["std"], default-features = false }
lazy_static = "1.4.0"
